//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JmDict.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JmDict.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a,あ,ア
        ///i,い,イ
        ///u,う,ウ
        ///e,え,エ
        ///o,お,オ
        ///
        ///ka,か,カ
        ///ki,き,キ
        ///ku,く,ク
        ///ke,け,ケ
        ///ko,こ,コ
        ///
        ///sa,さ,サ
        ///shi,し,シ
        ///su,す,ス
        ///se,せ,セ
        ///so,そ,ソ
        ///
        ///ta,た,タ
        ///chi,ち,チ
        ///tsu,つ,ツ
        ///te,て,テ
        ///to,と,ト
        ///
        ///na,な,ナ
        ///ni,に,ニ
        ///nu,ぬ,ヌ
        ///ne,ね,ネ
        ///no,の,ノ
        ///
        ///ha,は,ハ
        ///hi,ひ,ヒ
        ///fu,ふ,フ
        ///he,へ,ヘ
        ///ho,ほ,ホ
        ///
        ///ma,ま,マ
        ///mi,み,ミ
        ///mu,む,ム
        ///me,め,メ
        ///mo,も,モ
        ///
        ///ya,や,ヤ
        ///yu,ゆ,ユ
        ///yo,よ,ヨ
        ///
        ///ra,ら,ラ
        ///ri,り,リ
        ///ru,る,ル
        ///re,れ,レ
        ///ro,ろ,ロ
        ///
        ///wa,わ,ワ
        ///#wi,ゐ,ヰ
        ///#we,ゑ,ヱ
        ///wo,を,ヲ
        ///
        ///n,ん,ン
        ///.
        /// </summary>
        internal static string TheKana {
            get {
                return ResourceManager.GetString("TheKana", resourceCulture);
            }
        }
    }
}
